apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: cicdflux
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80


# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: hello
#   namespace: cicdflux
#   labels:
#     app: hello
# spec:
#   selector:
#     matchLabels:
#       app: hello
#   template:
#     metadata:
#       labels:
#         app: hello
#     spec:
#       containers:
#       - name: hello
#         image: linuxacademycontent/gitops:hellov1.2.2
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: hello-service
#   namespace: cicdflux
# spec:
#   selector:
#     app: hello
#   ports:
#   - protocol: TCP
#     port: 8000
#     nodePort: 32321
#   type: NodePort
